services:
  Prembot:
    build: .
    environment:
      API_ID: "API_ID"
      API_HASH: "API_HASH"
      BOT_TOKEN: "BOT_TOKEN"
      OWNER: "OWNER"
      FFMPEG: "FFMPEG"
      THUMBNAIL: "THUMBNAIL"
